######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 14 10:11:35 2014
######################################################################

TEMPLATE = app
TARGET = show_grayscale
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
